name = "quaternion"
version = "1.0.0"

description = "A simple quaternion implementation made with and for Gleam. Heavily inspired by the Rust quaternion crate."
licences = ["Apache-2.0", "MIT"]
repository = { type = "github", user = "PiaCOS", repo = "quaternion_gleam" }


[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_community_maths = ">= 1.1.1 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
